application: dnesudeda
version: 1
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /images
  static_dir: images

- url: .*
  script: main.py

libraries:
- name: django
  version: "1.2"

